import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { supabase } from '../services/supabaseClient';
import './ArticlePage.css';

const ArticlePage = () => {
  const { slug } = useParams();
  const [article, setArticle] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchArticle = async () => {
      setLoading(true);
      const { data, error } = await supabase
        .from('articles')
        .select('*')
        .eq('slug', slug)
        .single(); // .single() is crucial for getting one object, not an array

      if (error) {
        console.error('Error fetching article:', error);
        setError('Failed to load the article.');
      } else if (data) {
        setArticle(data);
      } else {
        setError('Article not found.');
      }
      setLoading(false);
    };

    fetchArticle();
  }, [slug]);

  if (loading) {
    return <div className="loader">Loading article...</div>;
  }

  if (error) {
    return (
      <div className="error-message">
        <p>{error}</p>
        <Link to="/">Go back to Home</Link>
      </div>
    );
  }

  if (!article) {
    return null; // Should be covered by error state, but as a fallback.
  }

  // The content from the database is expected to be safe HTML
  // generated by a trusted source (the admin's text editor).
  const createMarkup = (htmlString) => {
    return { __html: htmlString };
  };

  return (
    <>
      <Helmet>
        <title>{article.title}</title>
        <meta name="description" content={article.snippet || 'An article from SaveMoreMoney.in'} />
      </Helmet>
      <article className="article-page">
        <header className="article-header">
          <h1>{article.title}</h1>
          <p className="article-meta">
            By {article.author_name || 'Mausaji'} on {new Date(article.created_at).toLocaleDateString()}
          </p>
        </header>
        {article.image_url && <img src={article.image_url} alt={article.title} className="article-banner-image" />}
        <div 
          className="article-content"
          dangerouslySetInnerHTML={createMarkup(article.content)}
        />
      </article>
    </>
  );
};

export default ArticlePage;
